language: php

source_key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRW93SUJBQUtDQVFFQXVhYmIyMFdjN1VvK2I3TFdpa0ZTaXBhVFpPZXdJVUp0T3RLRG83cFk5dm9FWlVzUQ0KRWpldjI3bS9PYlpBZUlJZnBHb1p5S0xkYi9JckJYQ1ZvcHV4eTFTUUVKYVg2THhVNlJ4YWdGZ1IvL1VVQWM3SA0KRFFQL1VwQk1VR01sdGY5WW83dFcrYWtlNURlZk5HMGdKVTMzWE12YnZ4RElkRVUwNWcwWUZhTmtteFp6T2prRg0KcFRMU1FSeHpsbzJURlZ5MnozVEd5Y0Fza20yaTNSMVo4NmNZS3dIbzZhSDk5WVBrK3Y4RUhqRm93bGJRR0MvTA0KNXZCWkFBZWRGYVA3alBLL29GWVN3M2cyRFEvSmpxaHI5ZFF6djl3MnJvR2J4WXZTL2dFK0Nuc2paZUhQVnk2Lw0KS3dhem9xbUZDNHFZTlJoK3dpRFNiMFg2UFBvalp5clB5VGN4cXdJREFRQUJBb0lCQUNnbGFRMjF0QVdzTkd3Nw0KSkNHcGxvdlptKzRLSEJCVktRRzdYRFFmcS9WY2cyN1VHSm1YNlROK3ExZHpqZVdCWGc1VDAxZUx3STdnczJUdA0KdjYzMk5UQmZEUGhKV0hnL29hejNNS3JvWUp3VkIwcU15SWFNQXI1NzdjVEVhL2M3VEpPN2cwZGh4d2hhN3RhTA0KY3BRZWxBdEJHamZyRFMzM2VVVDJOK3NWOWorQzhQUElrRjlFRmZDK3Y3SjBVZm9NaHJDVnRGTmRuL0VZUTZ3Yg0KZmNaM3RuTWwwNFBhS2Q0dGhjaHFzcm1ROEZmZHlBZS9wSm9mUjF4VHR0MXRXT1pTUTl4aDFqcXJlemx5RFdkZw0KT1ZDMDhXMDVxNUliK215a05ESEdBUVo5dnl0cDgvb21wUnZkcFcxVzNWZFZjbmJ3Yk45REJtcG8xNHd6c0NtbQ0KeXJET0tjRUNnWUVBNHNjYVBFWU44aVdNNWpmcnBRNXNBQjFUK05YNGxMaHpQYXNZZ0ZYVXlJUlVYbmIxek1oSg0KZm83ZVlVNVNVcms5WXFNMDNxVHJpZityajVNU1A0ZmJoYklKZXNtLzl2NURkdVFST243UDZRK2pQbmFLVzJ2Sg0KRy94L1ZCNDRFTWNudXJiZExIdEFHTHRVMUdxeHpmSFdkVzF2QW40R1NMV1FVOHB2YU5idFFra0NnWUVBMFpNYQ0KRmxPVEwrOUJnamg3US9mTE15dmU5cTlSbk82MkxDM3FYdVJRMERhdGE2TU5vaHIxWmFvdm03bnBkTkhicHJwSA0KWGN5dHR1QVVCMnVFRzhPU0JVZ0NhYWFZYTNwYzdSOUExZmtiaFBXSUV4bjg4eXZDUkNnZjBCNXQ0OW1ZTkRNcQ0KZnc5a1VKSkgvelBEY1R6R2FVcVVxY1FIemcwRzR4alFJaGcxRkZNQ2dZRUF3djNOcWl2V1MvSkxyNXcvcXlHMg0KYlhiS1FEakRVQ1UxT2I1SEIvcEZSdEM1dHF2MDk4cnpuclY3c3hGa0thc0xoQ2V2Q3cybFZYZ1g3UkRaYlBVRg0KSlhVTFA1Ly94b0drUXJNaHVUbFd6aC9iRHBkZ3FmRUk4RjV3b1VTR2txNmJrNmt1amRQQUxrUE5VZ1FYdEd3UQ0KS2RJWjFIdkdMWGlvaTlPUmJnVDM1cmtDZ1lCWGVkb3F0WW03T1ZlVG5qVzlZZ0c4QXpUV3JNa1pBdjZoSkMwdQ0KbklncTBKZkVWTlBNOVFtMi9MbFFlK0k1TTV0R1ZYeVNaMnVlNkpzVG1jb1R1S2NMYzBvbWhUWWJyb0I1TFZGbg0KdnNuQXpxZVVxWVZPanRaUWtwcnN5TGEvbzBTSGpVL1FwMEVNN0hJRzBMbGtXNlRKc0NxclRicWdSQW02NHRHRg0KV2F0V0p3S0JnSEVudHZuc3V1WVJLa3hKbDFWZnJ1WC9ZVFk1NXNqSGlEOWhycGFvY3dBWk9Nb0RUakk3MFk2Kw0KTDJtUE1sVVdqL3BWNGdSZjV2R1JCNWxwMm55c1Fkdmd4bFhIZVFMWm1Lb2FVTWdnNjIxN3NFM21CL0R3enZPKw0KSWVjUDNBY3h4ZDdWd1RIYktHSWdiMkNXL2ttc3gwNHVMclMrK01tYzFWTkdJSTVBcWF6dA0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0NCg=="

cache:
  directories:
    - ~/.composer/cache

php:
  - 5.4

before_install:
  - phpenv config-add .travis.php.ini
  - composer self-update

install:
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

after_script:
  - ./bin/ocular code-coverage:upload --access-token="0ab85d09ea536dc6a7f03316b495cc078d8bee02c7c74974bbfd1fe280425a16" --format=php-clover build/logs/clover.xml
