language: php

sudo: false

php:
  - 5.4

before_install:
  - phpenv config-add .travis.php.ini
  - composer self-update

install:
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN=36b43abecd81c1051eb8d0212fd459c5f5df7ca806293c9862d24e498844eff3 ./bin/test-reporter
