parameters:
    open_orchestra_user.display.login.class: OpenOrchestra\UserBundle\DisplayBlock\LoginStrategy

services:
    open_orchestra_user.display.login:
        class: '%open_orchestra_user.display.login.class%'
        arguments:
            - '@security.csrf.token_manager'
            - '@security.token_storage'
        tags:
            - { name: open_orchestra_display.display_block.strategy }
