parameters:
    open_orchestra_user.display.login.class: OpenOrchestra\UserBundle\DisplayBlock\LoginStrategy

services:
    open_orchestra_user.display.login:
        class: %open_orchestra_user.display.login.class%
        arguments:
            - @form.csrf_provider
            - @security.context
        tags:
            - { name: open_orchestra_display.display_block.strategy }
