parameters:
    open_orchestra_user.type.change_password.class: OpenOrchestra\UserBundle\Form\Type\ChangePasswordUserType

services:
    open_orchestra_user.type.change_user_password:
        class: '%open_orchestra_user.type.change_password.class%'
        arguments:
            - '%open_orchestra_user.document.user.class%'
        tags:
            - { name: form.type, alias: oo_user_change_password }
