parameters:
    open_orchestra_user.type.api_client.class: OpenOrchestra\UserBundle\Form\Type\ApiClientType
services:
    open_orchestra_user.type.api_client:
        class: %open_orchestra_user.type.api_client.class%
        arguments:
            - %open_orchestra_user.document.api_client.class%
        tags:
            - { name: form.type, alias: api_client }
