resolve_target_documents:
    Symfony\Component\Security\Core\User\UserInterface: OpenOrchestra\UserBundle\Document\User
    OpenOrchestra\UserBundle\Model\ApiClientInterface: OpenOrchestra\UserBundle\Document\ApiClient
