parameters:
    open_orchestra_user.repository.user.class: OpenOrchestra\UserBundle\Repository\UserRepository
    open_orchestra_user.document.user.class: %fos_user.model.user.class%
    open_orchestra_user.repository.group.class: OpenOrchestra\UserBundle\Repository\GroupRepository
    open_orchestra_user.document.group.class: OpenOrchestra\UserBundle\Document\Group
    open_orchestra_user.repository.api_client.class: OpenOrchestra\UserBundle\Repository\ApiClientRepository
    open_orchestra_user.document.api_client.class: OpenOrchestra\UserBundle\Document\ApiClient
    open_orchestra_user.repository.access_token.class: OpenOrchestra\UserBundle\Repository\AccessTokenRepository
    open_orchestra_user.document.access_token.class: OpenOrchestra\UserBundle\Document\AccessToken
    open_orchestra_user.domain_manager.api_client.class: OpenOrchestra\UserBundle\DomainManager\ApiClientManager
    open_orchestra_user.document.authorization.class: OpenOrchestra\UserBundle\Document\Authorization

services:
    open_orchestra_user.repository.user:
        class: %open_orchestra_user.repository.user.class%
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getRepository
        arguments:
            - %open_orchestra_user.document.user.class%
    open_orchestra_user.repository.group:
        class: %open_orchestra_user.repository.group.class%
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getRepository
        arguments:
            - %open_orchestra_user.document.group.class%
    open_orchestra_user.repository.api_client:
        class: %open_orchestra_user.repository.api_client.class%
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getRepository
        arguments:
            - %open_orchestra_user.document.api_client.class%
    open_orchestra_user.repository.access_token:
        class: %open_orchestra_user.repository.access_token.class%
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getRepository
        arguments:
            - %open_orchestra_user.document.access_token.class%
    open_orchestra_user.domain_manager.api_client:
        class: %open_orchestra_user.domain_manager.api_client.class%
        arguments:
            - @doctrine.odm.mongodb.document_manager
            - %open_orchestra_user.document.api_client.class%
