parameters:
    open_orchestra_user.repository.user.class: OpenOrchestra\UserBundle\Repository\UserRepository
    open_orchestra_user.document.user.class: OpenOrchestra\UserBundle\Document\User

services:
    open_orchestra_user.repository.user:
        class: %open_orchestra_user.repository.user.class%
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getRepository
        arguments:
            - %open_orchestra_user.document.user.class%
