parameters:
    open_orchestra_user.twig_extension.display_layout.class: OpenOrchestra\UserBundle\Twig\DisplayLayoutExtension

services:
    open_orchestra_user.twig_extension.display_layout:
        class: %open_orchestra_user.twig_extension.display_layout.class%
        arguments:
            - @service_container
        tags:
            - { name: twig.extension}
