OpenOrchestra\UserBundle\Document\User:
    properties:
        lastName:
            - NotBlank: { groups: [Registration, Profile]}
        firstName:
            - NotBlank: { groups: [Registration, Profile]}
