OpenOrchestra\UserBundle\Document\User:
    properties:
        lastName:
            - NotBlank: { groups: [Registration, Profile]}
        firstName:
            - NotBlank: { groups: [Registration, Profile]}
        plainPassword:
            - OpenOrchestra\UserBundle\Validator\Constraints\ComplexUserPassword: { groups: [Registration, UpdatePassword]}
