parameters:
    open_orchestra_user.validator.complex_user_password.class: OpenOrchestra\UserBundle\Validator\Constraints\ComplexUserPasswordValidator

services:
    validator.complex_user_password:
        class: '%open_orchestra_user.validator.complex_user_password.class%'
        tags:
            - { name: validator.constraint_validator }
